const airlineOptions = [
    'American Airlines',
    'Delta Air Lines',
    'United Airlines',
    'Southwest Airlines',
    'Alaska Airlines',
    'JetBlue Airlines',
    'Spirit Airlines',
    'Frontier Airlines',
    'TUI',
    'Air Canada',
    'WestJet',
    'KLM Royal Dutch Airlines',
    'Lufthansa',
    'Iberia',
    'British Airways',
    'Aeromexico',
    'Copa Airlines',
    'TACA Airlines',
    'Avianca',
    'Air France',
    'Air Transat',
    'Edelweiss Air',
    'Iberojet',
    'Evelop',
    'Sun Country Airlines',
    'Sunwing Airlines',
    'Thomson Airways',
    'Volaris',
    'Wingo',
    // Add more airlines as needed
  ];
  
  export default airlineOptions;