/*
-- Query: SELECT * FROM route_information
LIMIT 0, 1000

-- Date: 2025-02-03 10:06
*/
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (1,'LIR - Liberia Airport','360 Splendor Pacifico Residences Flamingo',99,0,'360 Pacifico',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (2,'LIR - Liberia Airport','Andaz Costa Rica at Peninsula Papagayo',79,0,'Andaz',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (3,'LIR - Liberia Airport','Azura Beach Resort, Samara',149,0,'Azura - Samara',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (4,'LIR - Liberia Airport','Bahia del Sol Beachfront Hotel, Potrero',99,0,'Bahia del Sol',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (5,'LIR - Liberia Airport','Borinquen Thermal Resort',129,0,'Borinquen',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (6,'LIR - Liberia Airport','Buena Vista del Rincon Hotel & Spa',129,0,'Buena Vista',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (7,'LIR - Liberia Airport','Cala Luna Boutique Hotel & Villas',99,0,'Cala Luna',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (8,'LIR - Liberia Airport','Capitan Suizo Beachfront Hotel',99,0,'Cpt. Suizo',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (9,'LIR - Liberia Airport','Casa Chameleon at Las Catalinas',99,0,'Chameleon',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (10,'LIR - Liberia Airport','CC Beach Front Hotel',59,0,'CC Beach',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (11,'LIR - Liberia Airport','Coco Beach / Playas del Coco',69,0,'Coco',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (12,'LIR - Liberia Airport','Condovac La Costa',69,0,'Condovac',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (13,'LIR - Liberia Airport','Dreams Las Mareas Resort',129,0,'Dreams',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (14,'LIR - Liberia Airport','El Mangroove Papagayo',59,0,'El Mangroove',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (15,'LIR - Liberia Airport','Exclusive Resorts Peninsual Papagayo',99,0,'Exclusive - Papagayo',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (16,'LIR - Liberia Airport','Flamingo Marina Resort',99,0,'Flamingo Marina',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (17,'LIR - Liberia Airport','Four Seasons Costa Rica at Peninsula Papagayo',99,0,'Four Seasons',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (18,'LIR - Liberia Airport','Hacienda Pinilla Guanacaste',119,0,'Hacienda Pinilla',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (19,'LIR - Liberia Airport','Hideaway Rio Celeste Hotel',189,0,'Hideaway',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (20,'LIR - Liberia Airport','Hotel Bosque del Mar, Playa Hermosa',69,0,'Bosque del Mar',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (21,'LIR - Liberia Airport','Hotel Hacienda Guachipelin',89,0,'Hacienda',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (22,'LIR - Liberia Airport','Hotel RIU Guanacaste',79,0,'RIU Guanacaste',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (23,'LIR - Liberia Airport','Hotel RIU Palace Costa Rica',79,0,'RIU Palace',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (24,'LIR - Liberia Airport','JW Marriott Guanacaste',119,0,'Marriott Guan.',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (25,'LIR - Liberia Airport','Las Catalinas',99,0,'Las Catalinas',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (26,'LIR - Liberia Airport','Margaritaville Beach Resort Flamingo',99,0,'Margaritaville',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (27,'LIR - Liberia Airport','Marina Papagayo',69,0,'Marina',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (28,'LIR - Liberia Airport','Mother Earth Vegan Hotel Tamarindo',99,0,'Mother Earth',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (29,'LIR - Liberia Airport','Nicaragua Border (PeÃ±as Blancas)',129,0,'PeÃ±as Blancas',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (30,'LIR - Liberia Airport','Occidental Papagayo',69,0,'Occ. Papagayo',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (31,'LIR - Liberia Airport','Occidental Tamarindo',109,0,'Occ. Tamarindo',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (32,'LIR - Liberia Airport','Ocho Artisan Bungalows Tamarindo',99,0,'Ocho Tamarindo',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (33,'LIR - Liberia Airport','Ocotal Beach',79,0,'Ocotal',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (34,'LIR - Liberia Airport','Planet Hollywood Costa Rica',69,0,'Planet Hollywood',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (35,'LIR - Liberia Airport','Playa Avellanas Hotels & Airbnbs',129,0,'Playa Avellanas',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (36,'LIR - Liberia Airport','Playa Grande Hotels & Airbnbs',109,0,'Playa Grande',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (37,'LIR - Liberia Airport','Playa Langosta',109,0,'Playa Langosta',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (38,'LIR - Liberia Airport','Playa Negra Hotels & Airbnbs',129,0,'Playa Negra',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (39,'LIR - Liberia Airport','Punta San Francisco Playa Langosta',99,0,'Punta San Francisco',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (40,'LIR - Liberia Airport','Reserva Conchal',99,0,'Res. Conchal',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (41,'LIR - Liberia Airport','Rio Perdido Hotel & Thermal River',129,0,'Rio Perdido',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (42,'LIR - Liberia Airport','Rip Jack Inn Playa Grande',99,0,'Rip Jack',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (43,'LIR - Liberia Airport','Rythmia Life Advacenment Center',119,0,'Rythmia',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (44,'LIR - Liberia Airport','Samara Hotels & Airbnbs',149,0,'Samara',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (45,'LIR - Liberia Airport','Santarena Hotel at Las Catalinas',99,0,'Santarena',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (46,'LIR - Liberia Airport','Secrets Papagayo Costa Rica',59,0,'Secrets Papagayo',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (47,'LIR - Liberia Airport','Sunrise Condominiums Tamarindo',99,0,'Sunrise Tamarindo',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (48,'LIR - Liberia Airport','Tamarindo Diria Beach Resort',99,0,'Diria',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (49,'LIR - Liberia Airport','Ten North Tamarindo Beach Hotel',99,0,'Ten North',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (50,'LIR - Liberia Airport','The Westin Reserva Conchal',99,0,'Westin Conchal',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (51,'LIR - Liberia Airport','Villas Sol Beach Resort',69,0,'Villas Sol',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (52,'LIR - Liberia Airport','W Costa Rica - Reserva Conchal',99,0,'W - Conchal',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (53,'LIR - Liberia Airport','Waldorf Astoria Punta Cacique Costa Rica',79,0,'Waldor Astoria',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (54,'LIR - Liberia Airport','Wyndham Tamarindo',99,0,'Wyndham Tamarindo',1);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (55,'LIR - Liberia Airport','Arenal Springs Resort & Spa',199,0,'Arenal Springs',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (56,'LIR - Liberia Airport','Barcelo Tambor Costa Rica',249,0,'Barcelo Tambor',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (57,'LIR - Liberia Airport','Bodhi Tree Yoga Resort',199,0,'Bodhi Tree',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (58,'LIR - Liberia Airport','Florblanca Resort Santa Teresa',309,0,'Florblanca Resort',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (59,'LIR - Liberia Airport','Hotel Amor de Mar Montezuma',309,0,'Hotel Amor',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (60,'LIR - Liberia Airport','Hotel Boutique Lagarta Lodge Nosara',209,0,'Hotel Boutique',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (61,'LIR - Liberia Airport','Hotel Nantipa Santa Teresa',309,0,'Hotel Nantipa',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (62,'LIR - Liberia Airport','Hotel Tropico Latino Santa Teresa',309,0,'Hotel Tropico',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (63,'LIR - Liberia Airport','Jaco Beach',259,0,'Jaco',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (64,'LIR - Liberia Airport','La Fortuna Hotels & Airbnbs',199,0,'La Fortuna',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (65,'LIR - Liberia Airport','Lost Iguana Resort',189,0,'Lost Iguana',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (66,'LIR - Liberia Airport','Manuel Antonio Hotels & Airbnbs',339,0,'Manuel Antonio',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (67,'LIR - Liberia Airport','Monteverde Hotels & Airbnbs',209,0,'Monteverde',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (68,'LIR - Liberia Airport','Nayara Springs Costa Rica',199,0,'Nayara Springs',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (69,'LIR - Liberia Airport','Nayara Tent Camp',209,0,'Nayara Tent',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (70,'LIR - Liberia Airport','Punta Islita Autograph Collection',229,0,'PI Augograph',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (71,'LIR - Liberia Airport','SJO - San Jose Airport',279,0,'SJO',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (72,'LIR - Liberia Airport','The Harmony Hotel Nosara',199,0,'Harmony Nosara',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (73,'LIR - Liberia Airport','The Springs Resort & Spa Arenal',209,0,'Springs - Arenal',2);
INSERT INTO `` (`routeID`,`startcity`,`endcity`,`stdrate`,`duration`,`endcity_shortname`,`addlpassengertype`) VALUES (74,'LIR - Liberia Airport','Ylang Ylang Beach Resort',309,0,'Ylang Ylang',2);
